controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_index:
    path:       /api/index
    controller: App\Controller\ApiController::index
    methods:    GET